tweaked the 'ocf:heartbeat:VirtualDomain' and 'stonith:external/sbd' RA scripts for better handling

diff --git a/misc/resource-agents-4.2.0.patch b/misc/resource-agents-4.2.0.patch
--- a/misc/resource-agents-4.2.0.patch
+++ b/misc/resource-agents-4.2.0.patch
@@ -1,14 +1,3 @@
---- a/heartbeat/VirtualDomain	2021-09-14 07:56:25.201636489 -0400
-+++ b/heartbeat/VirtualDomain	2021-09-19 11:11:06.856157215 -0400
-@@ -460,7 +460,7 @@
- 		try=$(($try + 1 ))
- 		status=$(LANG=C virsh $VIRSH_OPTIONS domstate $DOMAIN_NAME 2>&1 | tr 'A-Z' 'a-z')
- 		case "$status" in
--			*"error:"*"domain not found"|*"error:"*"failed to get domain"*|"shut off")
-+			*"error:"*"domain not found"*|*"error:"*"failed to get domain"*|"shut off")
- 				# shut off: domain is defined, but not started, will not happen if
- 				#   domain is created but not defined
- 				# "Domain not found" or "failed to get domain": domain is not defined
 --- a/heartbeat/Raid1	2018-10-24 04:12:09.000000000 -0400
 +++ b/heartbeat/Raid1	2023-10-11 10:54:15.969396345 -0400
 @@ -182,7 +182,7 @@
@@ -77,3 +66,49 @@
  		# TODO: At this stage, there's nothing to actually do
  		# here. Either this worked or it did not.
  	fi
+--- a/heartbeat/VirtualDomain	2018-10-24 04:12:09.000000000 -0400
++++ b/heartbeat/VirtualDomain	2023-11-25 18:20:48.568626132 -0500
+@@ -460,7 +460,7 @@
+ 		try=$(($try + 1 ))
+ 		status=$(LANG=C virsh $VIRSH_OPTIONS domstate $DOMAIN_NAME 2>&1 | tr 'A-Z' 'a-z')
+ 		case "$status" in
+-			*"error:"*"domain not found"|*"error:"*"failed to get domain"*|"shut off")
++			*"error:"*"domain not found"*|*"error:"*"failed to get domain"*|"shut off")
+ 				# shut off: domain is defined, but not started, will not happen if
+ 				#   domain is created but not defined
+ 				# "Domain not found" or "failed to get domain": domain is not defined
+@@ -733,9 +733,10 @@
+ 			fi
+ 
+ 			# The "shutdown_timeout" we use here is the operation
+-			# timeout specified in the CIB, minus 5 seconds
+-			shutdown_timeout=$(( $NOW + ($OCF_RESKEY_CRM_meta_timeout/1000) -5 ))
++			# timeout specified in the CIB, minus 15 seconds
++			shutdown_timeout=$(( $NOW + ($OCF_RESKEY_CRM_meta_timeout/1000) -15 ))
+ 			# Loop on status until we reach $shutdown_timeout
++			loop_cnt=1
+ 			while [ $NOW -lt $shutdown_timeout ]; do
+ 				VirtualDomain_status
+ 				status=$?
+@@ -749,12 +750,21 @@
+ 						# waiting (until shutdown_timeout
+ 						# expires)
+ 						sleep 1
++						# The guest OS may not have received the ACPI shutdown event, so try again every 20s
++						if [ $(expr ${loop_cnt} % 20) -eq 0 ]; then
++							if [ -n "${OCF_RESKEY_CRM_shutdown_mode}" ]; then
++								shutdown_opts="--mode ${OCF_RESKEY_CRM_shutdown_mode}"
++							fi
++							ocf_log info "Issuing additional graceful shutdown request for domain ${DOMAIN_NAME}."
++							virsh $VIRSH_OPTIONS shutdown ${DOMAIN_NAME} $shutdown_opts
++						fi
+ 						;;
+ 					*)
+ 						# Something went wrong. Bail out and
+ 						# resort to forced stop (destroy).
+ 						break;
+ 				esac
++				loop_cnt=$(expr ${loop_cnt} + 1)
+ 				NOW=$(date +%s)
+ 			done
+ 			;;
