rework of InfiniBand setup... new rc.openibd rc script for loading IB modules and rc.opensm for IB subnet manager; enabled IPoIB and switched all IB kernel options to modules (for use with new rc.openibd setup); added "performance tweaks" to sysctl.conf that are hopefully universal (from OFED package); more SCST RA tweaks; removed IB modules from RA and SCST rc script

diff --git a/misc/ocf/scst b/misc/ocf/scst
--- a/misc/ocf/scst
+++ b/misc/ocf/scst
@@ -13,56 +13,56 @@
 # Initialization
 : ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
 . ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs
-MODULES="ib_ipath mlx4_ib ib_mthca ib_qib \
-scst qla2x00tgt iscsi-scst ib_srpt \
+MODULES="scst qla2x00tgt iscsi-scst ib_srpt \
 scst_disk scst_vdisk scst_tape scst_changer fcst"
 SCST_CFG="/etc/scst.conf"
 PRE_SCST_CONF="/etc/pre-scst_xtra_conf"
 POST_SCST_CONF="/etc/post-scst_xtra_conf"
 SCST_SYSFS="/sys/kernel/scst_tgt"
 
-SCST_start() {
+scst_start() {
 	# Exit immediately if configuration is not valid
-	SCST_validate_all || exit $?
+	scst_validate_all || exit $?
 
 	# If resource is already running, bail out early
-	if SCST_monitor; then
+	if scst_monitor; then
 		ocf_log info "Resource is already running."
 		return $OCF_SUCCESS
 	fi
 
 	# If our pre-SCST file exists, run it
 	if [ -f $PRE_SCST_CONF]; then
-		ocf_log debug "Pre-SCST user config. file found; running..."
-		ocf_run -warn "sh $PRE_SCST_CONF"
+		ocf_log info "Pre-SCST user config. file found; running..."
+		ocf_run -warn sh $PRE_SCST_CONF
 	fi
 
 	# Load all modules
-	ocf_log debug "Loading kernel modules..."
+	ocf_log info "Loading kernel modules..."
 	for i in $MODULES; do
-		ocf_run "modprobe $i" || exit $OCF_ERR_GENERIC
+		ocf_log debug "Module: $i"
+		ocf_run modprobe $i || exit $OCF_ERR_GENERIC
 	done
 
 	# Start the daemons
-	ocf_log debug "Starting daemons..."
-	ocf_run "iscsi-scstd" || exit $OCF_ERR_GENERIC
-	ocf_run "lldpad -d" || exit $OCF_ERR_GENERIC
-	ocf_run "fcoemon -s" || exit $OCF_ERR_GENERIC
+	ocf_log info "Starting daemons..."
+	ocf_run iscsi-scstd || exit $OCF_ERR_GENERIC
+	ocf_run lldpad -d || exit $OCF_ERR_GENERIC
+	ocf_run fcoemon -s || exit $OCF_ERR_GENERIC
 
 	# Configure SCST
 	if [ -f $SCST_CFG ]; then
-		ocf_log debug "Applying SCST configuration..."
-		ocf_run "scstadmin -config $SCST_CFG" || exit $OCF_ERR_GENERIC
+		ocf_log info "Applying SCST configuration..."
+		ocf_run scstadmin -config $SCST_CFG || exit $OCF_ERR_GENERIC
 	fi
 
 	# If our post-SCST file exists, run it
 	if [ -f $POST_SCST_CONF ]; then
-		ocf_log debug "Post-SCST user config. file found; running..."
-		ocf_run -warn "sh $POST_SCST_CONF"
+		ocf_log info "Post-SCST user config. file found; running..."
+		ocf_run -warn sh $POST_SCST_CONF
 	fi
 
 	# Make sure the resource started correctly
-	while ! SCST_monitor; do
+	while ! scst_monitor; do
 		ocf_log debug "Resource has not started yet, waiting..."
 		sleep 1
 	done
@@ -70,7 +70,7 @@ SCST_start() {
 	# If we are using ALUA, be sure we are in Slave mode (offline)
 	if ocf_is_true $OCF_RESKEY_alua; then
 		target_groups="$SCST_SYSFS/device_groups/$OCF_RESKEY_device_group/target_groups"
-		ocf_run "echo offline > $target_groups/$OCF_RESKEY_local_tgt_grp/state" || \
+		ocf_run echo offline > $target_groups/$OCF_RESKEY_local_tgt_grp/state || \
 		exit $OCF_ERR_GENERIC
 	fi
 
@@ -78,22 +78,22 @@ SCST_start() {
 	return $OCF_SUCCESS
 }
 
-SCST_stop() {
+scst_stop() {
 	# Exit immediately if configuration is not valid
-	SCST_validate_all || exit $?
+	scst_validate_all || exit $?
 
 	# Check the current resource state
-	SCST_monitor
+	scst_monitor
 	local rc=$?
 	case "$rc" in
 	"$OCF_SUCCESS")
 		# Currently running; normal, expected behavior
-		ocf_log debug "Resource is currently running."
+		ocf_log info "Resource is currently running."
 		;;
 	"$OCF_RUNNING_MASTER")
 		# Running as a Master; need to demote before stopping
 		ocf_log info "Resource is currently running as Master."
-		SCST_demote || ocf_log warn "Demote failed, trying to stop anyway..."
+		scst_demote || ocf_log warn "Demote failed, trying to stop anyway..."
 		;;
 	"$OCF_NOT_RUNNING")
 		# Currently not running; nothing to do
@@ -103,12 +103,13 @@ SCST_stop() {
 	esac
 
 	# Save the SCST configuration, just in case
-	ocf_log debug "Saving SCST configuration..."
-	ocf_run "scstadmin -nonkey -write_config $SCST_CFG" || exit $OCF_ERR_GENERIC
+	ocf_log info "Saving SCST configuration..."
+	ocf_run scstadmin -nonkey -write_config $SCST_CFG || exit $OCF_ERR_GENERIC
 
 	# Stop all of the daemons and wait for each
+	ocf_log info "Stopping daemons..."
 	for i in "fcoemon lldpad iscsi-scstd"; do
-		ocf_run "killall -TERM $i" || exit $OCF_ERR_GENERIC
+		ocf_run killall -TERM $i || exit $OCF_ERR_GENERIC
 		while pidof $i > /dev/null 2>&1; do
 			ocf_log debug "The $i daemon is still running, waiting..."
 			sleep 1
@@ -116,12 +117,14 @@ SCST_stop() {
 	done
 
 	# Unload the modules (in reverse)
+	ocf_log info "Unloading kernel modules..."
 	for i in $(echo $MODULES | tr ' ' '\n' | tac | tr '\n' ' '); do
-		ocf_run "modprobe -r $i" || exit $OCF_ERR_GENERIC
+		ocf_log debug "Module: $i"
+		ocf_run modprobe -r $i || exit $OCF_ERR_GENERIC
 	done
 
 	# Make sure the resource stopped correctly
-	while SCST_monitor; do
+	while scst_monitor; do
 		ocf_log debug "Resource has not stopped yet, waiting..."
 		sleep 1
 	done
@@ -130,9 +133,9 @@ SCST_stop() {
 	return $OCF_SUCCESS
 }
 
-SCST_monitor() {
+scst_monitor() {
 	# Exit immediately if configuration is not valid
-	SCST_validate_all || exit $?
+	scst_validate_all || exit $?
 
 	# Check if SCST is loaded
 	local rc=$OCF_NOT_RUNNING
@@ -158,7 +161,7 @@ SCST_monitor() {
 	return $rc
 }
 
-SCST_validate_all() {
+scst_validate_all() {
 	# Test for required binaries
 	check_binary scstadmin
 
@@ -196,11 +199,11 @@ SCST_validate_all() {
 	return $OCF_SUCCESS
 }
 
-SCST_meta_data() {
+scst_meta_data() {
 	cat <<-EOF
 	<?xml version="1.0"?>
 	<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
-	<resource-agent name="SCST" version="0.1">
+	<resource-agent name="scst" version="0.1">
 	  <version>0.1</version>
 	  <longdesc lang="en">The SCST OCF resource agent for ESOS; includes SCST ALUA support.</longdesc>
 	  <shortdesc lang="en">SCST OCF RA script for ESOS.</shortdesc>
@@ -242,18 +245,18 @@ SCST_meta_data() {
 	EOF
 }
 
-SCST_usage() {
+scst_usage() {
 	echo "usage: $0 {start|stop|monitor|validate-all|promote|demote|reload|notify|meta-data}"
 	echo ""
 	echo "Expects to have a fully populated OCF RA-compliant environment set."
 }
 
-SCST_promote() {
+scst_promote() {
 	# Exit immediately if configuration is not valid
-	SCST_validate_all || exit $?
+	scst_validate_all || exit $?
 
 	# Test the resource's current state
-	SCST_monitor
+	scst_monitor
 	local rc=$?
 	case "$rc" in
 	"$OCF_SUCCESS")
@@ -268,7 +271,7 @@ SCST_promote() {
 	"$OCF_NOT_RUNNING")
 		# Currently not running; need to start before promoting
 		ocf_log info "Resource is currently not running."
-		SCST_start
+		scst_start
 		;;
 	*)
 		# Failed resource; let the cluster manager recover
@@ -280,15 +283,18 @@ SCST_promote() {
 	# Promote only makes sense if we are using ALUA
 	if ocf_is_true $OCF_RESKEY_alua; then
 		target_groups="$SCST_SYSFS/device_groups/$OCF_RESKEY_device_group/target_groups"
-		ocf_run "echo active > $target_groups/$OCF_RESKEY_local_tgt_grp/state" || \
+		ocf_run echo active > $target_groups/$OCF_RESKEY_local_tgt_grp/state || \
 		exit $OCF_ERR_GENERIC
+	else
+		ocf_log err "The ALUA parameters need to be configured before using MS."
+		exit $OCF_ERR_CONFIGURED
 	fi
 
 	# After the resource has been promoted, check whether the promotion worked
 	while true; do
-		SCST_monitor
+		scst_monitor
 		if [ $? -eq $OCF_RUNNING_MASTER ]; then
-			ocf_log debug "Resource was promoted successfully."
+			ocf_log info "Resource was promoted successfully."
 			break
 		else
 			ocf_log debug "Resource still awaiting promotion."
@@ -300,12 +306,12 @@ SCST_promote() {
 	return $OCF_SUCCESS
 }
 
-SCST_demote() {
+scst_demote() {
 	# Exit immediately if configuration is not valid
-	SCST_validate_all || exit $?
+	scst_validate_all || exit $?
 
 	# Test the resource's current state
-	SCST_monitor
+	scst_monitor
 	local rc=$?
 	case "$rc" in
 	"$OCF_RUNNING_MASTER")
@@ -332,18 +338,21 @@ SCST_demote() {
 	# Demote only makes sense if we are using ALUA
 	if ocf_is_true $OCF_RESKEY_alua; then
 		target_groups="$SCST_SYSFS/device_groups/$OCF_RESKEY_device_group/target_groups"
-		ocf_run "echo offline > $target_groups/$OCF_RESKEY_local_tgt_grp/state" || \
+		ocf_run echo offline > $target_groups/$OCF_RESKEY_local_tgt_grp/state || \
 		exit $OCF_ERR_GENERIC
+	else
+		ocf_log err "The ALUA parameters need to be configured before using MS."
+		exit $OCF_ERR_CONFIGURED
 	fi
 
 	# After the resource has been demoted, check whether the demotion worked
 	while true; do
-		SCST_monitor
+		scst_monitor
 		if [ $? -eq $OCF_RUNNING_MASTER ]; then
 			ocf_log debug "Resource still awaiting promotion."
 			sleep 1
 		else
-			ocf_log debug "Resource was demoted successfully."
+			ocf_log info "Resource was demoted successfully."
 			break
 		fi
 	done
@@ -352,7 +361,7 @@ SCST_demote() {
 	return $OCF_SUCCESS
 }
 
-SCST_notify() {
+scst_notify() {
 	local type_op="${OCF_RESKEY_CRM_meta_notify_type}-${OCF_RESKEY_CRM_meta_notify_operation}"
 	ocf_log debug "Received $type_op notification."
 	case "$type_op" in
@@ -370,50 +379,50 @@ SCST_notify() {
 # Make sure meta-data and usage always succeed
 case $__OCF_ACTION in
 meta-data)
-	SCST_meta_data
+	scst_meta_data
 	exit $OCF_SUCCESS
 	;;
 usage|help)
-	SCST_usage
+	scst_usage
 	exit $OCF_SUCCESS
 	;;
 esac
 
 # Anything other than meta-data and usage must pass validation
-SCST_validate_all || exit $?
+scst_validate_all || exit $?
 
 # Translate each action into the appropriate function call
 case $__OCF_ACTION in
 start)
-	SCST_start
+	scst_start
 	;;
 stop)
-	SCST_stop
+	scst_stop
 	;;
 status|monitor)
-	SCST_monitor
+	scst_monitor
 	;;
 notify)
-	SCST_notify
+	scst_notify
 	;;
 promote)
-	SCST_promote
+	scst_promote
 	;;
 demote)
-	SCST_demote
+	scst_demote
 	;;
 reload)
 	ocf_log info "Reloading..."
-	SCST_start
+	scst_start
 	;;
 validate-all)
 	;;
 migrate_to|migrate_from)
-	SCST_usage
+	scst_usage
 	exit $OCF_ERR_UNIMPLEMENTED
 	;;
 *)
-	SCST_usage
+	scst_usage
 	exit $OCF_ERR_UNIMPLEMENTED
 	;;
 esac
